repo:
  scanPath: ./preview-repos
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main

meta: 
  title: git-preview
  description: a static git web frontend but with images and html previews + code truncation
  syntaxHighlight: monokailight

server:
  name: localhost
  host: 127.0.0.1
  port: 5555
